# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/UISettingsDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(587, 176)
        Settings.setMinimumSize(QtCore.QSize(587, 176))
        Settings.setMaximumSize(QtCore.QSize(587, 176))
        self.gridLayoutWidget = QtWidgets.QWidget(Settings)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 571, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.create_db_table = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.create_db_table.setObjectName("create_db_table")
        self.gridLayout.addWidget(self.create_db_table, 0, 0, 1, 1)
        self.delete_db_table = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.delete_db_table.setObjectName("delete_db_table")
        self.gridLayout.addWidget(self.delete_db_table, 1, 0, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Settings)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 571, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.close_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/sfc-ui/ui/icons/cross-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon)
        self.close_btn.setIconSize(QtCore.QSize(24, 24))
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(Settings)
        self.close_btn.clicked.connect(Settings.accept)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Dialog"))
        self.create_db_table.setText(_translate("Settings", "Disable \"Create DB Table\" button"))
        self.delete_db_table.setText(_translate("Settings", "Disable \"Delete DB Table\" button"))
        self.close_btn.setText(_translate("Settings", "Close"))
import resources_rc
